name: periodic health check

on:
  # schedule:
  #   - corn: '0 23 1-31 1-12 0-6'
  push:
    branches:
      - master

jobs:
  health-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Checking the deployed application-url
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: "https://mypokemon11.herokuapp.com/health"
          max-attempts: 2
          retry-delay: 4s


    



        

        
