name: periodic health check

on:
  schedule:
    - corn: '45 0 * * *'

jobs:
  health-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Checking the deployed application-url
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: "https://mypokemon11.herokuapp.com/health"
          max-attempts: 2
          retry-delay: 4s


    



        

        
