name: testNotification
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: [master]
    types:  [opened , synchronize]


          
  notification:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: consoling ...
        run: |
          echo ${{job}}
          cat  ${{job.status}}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo, message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
        if: always()
    



        

        
