name: testNotification
on: 
  push:
    branches: 
      - testing

jobs:
  notification:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: checking job object
        env:
          JOB:  ${{toJson(job)}}
        run: echo date

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: all
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
        if: always()
    



        

        
